INSERT INTO artist(id, name, year_born, year_died) VALUES (1, 'Michelangelo', 1475, 1564);
INSERT INTO artist(id, name, year_born, year_died) VALUES (2, 'Johann Wolfgang von Goethe', 1749, 1832);
INSERT INTO artist(id, name, year_born, year_died) VALUES (3, 'Pablo Picasso', 1881, 1973);
INSERT INTO artist(id, name, year_born, year_died) VALUES (4, 'Vincent van Gogh', 1853, 1890);
INSERT INTO artist(id, name, year_born, year_died) VALUES (5, 'Klemens Brosch', 1894, 1926);
INSERT INTO artist(id, name, year_born, year_died) VALUES (6, 'George Orwell', 1903, 1950);
INSERT INTO artist(id, name, year_born, year_died) VALUES (7, 'Aldous Huxley', 1894, 1963);
INSERT INTO artist(id, name, year_born, year_died) VALUES (8, 'Leonardo da Vinci', 1452, 1519);

INSERT INTO great_work(name, year_finished, work_type, medium, pages, artist_id) VALUES ('David', 1504, 'VISUAL_ARTWORK', 'Marble', null, 1);
INSERT INTO great_work(name, year_finished, work_type, medium, pages, artist_id) VALUES ('The Creation of Adam', 1512, 'VISUAL_ARTWORK', 'Fresco', null, 1);
INSERT INTO great_work(name, year_finished, work_type, medium, pages, artist_id) VALUES ('Die Leiden des jungen Werthers', 1774, 'LITERATURE', null, 165, 2);
INSERT INTO great_work(name, year_finished, work_type, medium, pages, artist_id) VALUES ('Faust', 1808, 'LITERATURE', null, 136, 2);
INSERT INTO great_work(name, year_finished, work_type, medium, pages, artist_id) VALUES ('Guernica', 1937, 'VISUAL_ARTWORK', 'Oil', null, 3);
INSERT INTO great_work(name, year_finished, work_type, medium, pages, artist_id) VALUES ('Les Demoiselles d Avignon', 1907, 'VISUAL_ARTWORK', 'Oil', null, 3);
INSERT INTO great_work(name, year_finished, work_type, medium, pages, artist_id) VALUES ('Woman with Green Hat', 1947, 'VISUAL_ARTWORK', 'Oil', null, 3);
INSERT INTO great_work(name, year_finished, work_type, medium, pages, artist_id) VALUES ('The Starry Night', 1889, 'VISUAL_ARTWORK', 'Oil', null, 4);
INSERT INTO great_work(name, year_finished, work_type, medium, pages, artist_id) VALUES ('The Potato Eaters', 1885, 'VISUAL_ARTWORK', 'Oil', null, 4);
INSERT INTO great_work(name, year_finished, work_type, medium, pages, artist_id) VALUES ('Self-Portrait', 1889, 'VISUAL_ARTWORK', 'Oil', null, 4);
INSERT INTO great_work(name, year_finished, work_type, medium, pages, artist_id) VALUES ('Das Krokodil auf der Mondscheibe', 1911, 'VISUAL_ARTWORK', 'Ink', null, 5);
INSERT INTO great_work(name, year_finished, work_type, medium, pages, artist_id) VALUES ('Animal Farm', 1945, 'LITERATURE', null, 132, 6);
INSERT INTO great_work(name, year_finished, work_type, medium, pages, artist_id) VALUES ('Nineteen Eighty-Four', 1949, 'LITERATURE', null, 328, 6);
INSERT INTO great_work(name, year_finished, work_type, medium, pages, artist_id) VALUES ('Brave New World', 1931, 'LITERATURE', null, 311, 7);
INSERT INTO great_work(name, year_finished, work_type, medium, pages, artist_id) VALUES ('Mona Lisa', 1503, 'VISUAL_ARTWORK', 'Oil', null, 8);
INSERT INTO great_work(name, year_finished, work_type, medium, pages, artist_id) VALUES ('The Last Supper', 1498, 'VISUAL_ARTWORK', 'Fresco', null, 8);
